### ISSUE TITLE
Migration in progress

### ISSUE THREAD

**Issue by erikbosch** [eclipse-kuksa/kuksa-mock-provider#1]
This repo is supposed to be filled with the mock service from kuksa.val.services, seehttps://github.com/eclipse/kuksa.val.services/issues/119

This issue intends to track the progress

**Comment by erikbosch** [comment]
Migration result is now ready for review. I have tested mockprovider and the GUI, and there is a basic devcontainer for those who value that (I don't) which I have tested - I could get up a prompt in VScode and I could connect to Databroker.

@SebastianSchildt @eriksven @lukasmittag @mikehaller - feel free to take a look at this repo and check if you see some obvious problems

**Comment by mikehaller** [comment]
Thank you Erik!

Devcontainer builds, but the setup steps don't work out of the box.

I noticed that it's using `FROM python:3.11` as a base, which is odd for a devcontainer imho.

As a developer, I would prefer a known full system, like the base images for Debian provided by VSCode folks.
I guess it's a leftover, which we can take care later.

A devcontainer is supposed to be set up in a way so that every new user can just start with the "Build" or "How to run" steps from the readme - like, all necessary tools are properly installed in the devcontainer etc.

When running the `python3 -m pip install -r ./requirements.txt` steps in the current devcontainer (from python:3.11), i get the following warning:
```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

When I try to run `python3 mockprovider.py` it prints error messages due to the missing databroker. The readme does not state how to run databroker.

Imho that's okay, since it's not part of the migration to also make the devcontainer setup nicer, that's a different topic.

**Comment by erikbosch** [comment]
@mikehaller - do you have any preferred image to use as base? In general we should support Python 3.9 onwards so it should be possible to use quite many from https://github.com/devcontainers/images/tree/main/src/python. Maybe mcr.microsoft.com/devcontainers/python:3.11 ? 

And maybe there is a missunderstanding from my side concerning dev-containers, I thought dependencies should be installed as well so the dev-container has already done the pip commands, but I could remove that.

And in general for providers we do not say much on how to start databroker (compare with for example https://github.com/eclipse-kuksa/kuksa-python-sdk, https://github.com/eclipse-kuksa/kuksa-can-provider) it is sort of a per-requisite that you have Databroker (or whatever other server you want to use as server) running to be able to connect. But we could mention that your server/broker should be started and you need to know on which IP/port it runs. 

The warning on pip can be ignored iun this context I would say, but as I understand devcontainers have some mechanisms to define a different user.

**Comment by mikehaller** [comment]
Yes, you're right, that would be the base image being used when a user goes via VSCode > Add DevContainer > Select devcontainer configuration template.

Yes, devcontainer should have all tools and their dependencies preinstalled. And stuff required to debug/run/test the application-under-development. So in this case of the mock-service, I would expect the devcontainer to already "contain" the databroker somehow, since it's a pre-requisite/dependency. That could be a script to start databroker, a VSCode Task, or the devcontainer could even start the databroker already as a Docker instance. Depends a bit on how easy you want to make it for newbies to start coding vs., a veteran and what he may need. If a project becomes very complex, you may even have several different devcontainers to suite different scenarios.

If i would want to have pylint preinstalled, i wouldn't do that in the Dockerfile, i would first try to use the devcontainer features for it, e.g. this:

```
{
	"name": "Python 3",
	// Or use a Dockerfile or Docker Compose file. More info: https://containers.dev/guide/dockerfile
	"image": "mcr.microsoft.com/devcontainers/python:1-3.11-buster",
	"features": {
		"ghcr.io/devcontainers-contrib/features/pylint:2": {}
	}
}
```

Or if there are specific VSCode Extensions which must be installed, or are recommended. That stuff should be defined in the devcontainer. For some projects, you may even have recommended resources specified, such as minimum disk size and CPUs. That's handy if you know your project will only build with > X GB of RAM or disk space, so you just specify that in the devcontainer.

**Comment by erikbosch** [comment]
I think we need a wider discussion on what ambitions we want to have with devcontainers and what use-cases we want them to cover. My view is that we do not know what Databroker the user wants to run, if he wants to use the latest released one, a locally built one, what catalog he wants to use within Databroker and so on. Off course we could have one devcontainer for demo or test purposes which users can adapt as needed for their needs.

**Comment by erikbosch** [comment]
Migration considered finished
